import { LinhaLivro } from '@/componentes/LinhaLivro';
import { Menu } from '@/componentes/Menu';
import type {NextPage} from 'next';
import Head from 'next/head';
import React, { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css'
import _controleEditora from '../classes/controle/ControleEditora'
import Livro from '@/classes/modelo/Livro';
import {
    Router,
    useNavigate,
  } from "react-router-dom";

const baseUrl = 'http://localhost:3000/api/livros'

const controleEditora = new _controleEditora();

async function incluirLivro(livro : Livro){
    return fetch(baseUrl, {method: "POST",
    headers: {
        "Content-Type": "application/json",
      },
    body: JSON.stringify(livro)}).then((r) => r.json()).then((data) => {
        return data.ok;
    });
}


const LivroDados : NextPage = () => {

    let opcoes = controleEditora.getEditoras().map((editora) => {
        return {value: editora.codEditora, text: editora.nome}
    });

    let [titulo, setTitulo] = useState("");
    let [resumo, setResumo] = useState("");
    let [autores, setAutores] = useState("");
    let [codEditora, setCodEditora] = useState(opcoes[0].value)

    let tratarCombo = function(evento : any){
        setCodEditora(evento.target.value)
    }

    //const navigate = useNavigate();

    let incluir = function(evento : any){
        evento.preventDefault();
        let novoLivro = new Livro();
        novoLivro.codigo = 0;
        novoLivro.autores = autores.split('\n')
        novoLivro.titulo = titulo;
        novoLivro.resumo = resumo;
        novoLivro.codEditora = codEditora;
        incluirLivro(novoLivro);
        //navigate('/LivroLista');
    }

    return (
        <div className={styles.container}>
        <Head>
          <title>Loja Next</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Menu />
          <h1 className={styles.title}>Novo Livro</h1>
          <main className={styles.main}>
          <form onSubmit={incluir}>
            <div className="form-group">
                <label htmlFor="titulo">Titulo</label>
                <input onChange={(e) => setTitulo(e.target.value)} type="text" className="form-control" id="titulo"  placeholder="Titulo" />
            </div>

            <div className="form-group">
                <label htmlFor="resumo">Resumo</label>
                <textarea  onChange={(e : any) => setResumo(e.target.value)}  className="form-control" id="resumo"  placeholder="Resumo" />
            </div>


            <div className="form-group">
                <label htmlFor="editora">Editora</label>
                <select className="form-control" id="editora" onChange={tratarCombo}>
                    {opcoes.map((e)=>{
                        
                        return <option key={e.value} value={e.value}>{e.text}</option>

                    })}
                </select>
            </div>
            
            <div className="form-group">
                <label htmlFor="autores">Autores (1 por linha)</label>
                <textarea  onChange={(e) => setAutores(e.target.value)}  className="form-control" id="autores"  placeholder="Autores" />
            </div>


            <br />
            <button type="submit" className="btn btn-primary">Salvar dados</button>
            </form>
          </main>
      </div>
    )
}

export default LivroDados;